apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-web-app
  namespace: react-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-web-app
  template:
    metadata:
      labels:
        app: react-web-app
    spec:
      containers:
      - name: react-web-app
        image: hexxo/react-web-app
        ports:
        - containerPort: 3000