apiVersion: v1
kind: Service
metadata:
  name: react-web-app
  namespace: react-web-app
spec:
  selector:
    app: react-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer